### ISSUE TITLE
Filters should come on the top for mobile devices

### ISSUE THREAD

**Issue by mrswapnilsahu** [REAK-INFOTECH-LLP/hugo-personal-blog#15]
**Describe the bug**
Post filters (like filter by year, category) should come on the top of the blog posts in mobile devices

**To Reproduce**
Scroll down to 'till the end' in mobile device

**Expected behavior**
Should come on top of the blog posts.

**Screenshots**
![image](https://user-images.githubusercontent.com/23381895/96348446-66d90600-10c6-11eb-8ea9-94c6e3ce4764.png)

**Smartphone (please complete the following information):**
 - Device: for all mobile devices

**Comment by eclipsed-ninja** [comment]
Closing as its addressed in the latest PR
